name: e_commerce
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
<<<<<<< HEAD
  google_sign_in: ^6.1.5
=======
  fluid_bottom_nav_bar: ^1.4.0
>>>>>>> f381b94aa23eb9fa1b791183711129edcfe86f86
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/